---
title: "EcoTyper tutorials"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(readxl)
library(tidyverse)
library(janitor)
```

```{r}
setwd("/home/lythgo02/ecotyper/downloading_ecotyper_data/Tatlow_and_Piccolo_2016/")
```

```{r}
ecotype_assignment_3_median_all <- read_delim("Tatlow_and_Piccolo_2016/ecotyper_output/130522_tatlow_piccolo_2016_for_ecotyper_3_median_all/tatlow_picollo_2016_for_ecotyper_3_median_all_transcripts/Ecotypes/ecotype_assignment.txt", 
     delim = "\t", escape_double = FALSE, 
     trim_ws = TRUE) %>% 
  clean_names() %>% 
  dplyr::rename(assigned_ce = assignment_p)
```



```{r}
#matching the IDs
author_ecotype_abundances <-read_excel("/home/lythgo02/ecotyper/EcoTyper_source_code/1-s2.0-S0092867421010618-mmc6_table_s6_ecotype_abundances.xlsx", 
    sheet = "S6A", col_names = FALSE) 
 author_ecotype_abundances <- author_ecotype_abundances[-c(1:4),]  
  author_ecotype_abundances$...1 <-  str_replace_all(author_ecotype_abundances$...1, "\\.", "-") 
  author_ecotype_abundances <- author_ecotype_abundances %>% 
    row_to_names(row_number = 1) %>%  
   clean_names() 
   
  
 # author_ecotype_abundances$aliquot_barcode <- author_ecotype_abundances$na #rename 1st column to match TCGA_id_map
 author_ecotype_abundances <- author_ecotype_abundances %>% 
   dplyr::rename(assigned_ce = na_2,
                 aliquot_barcode = na)
  # dplyr::select(-"na", -"na_2")  %>% #remove unnecessary na column
   #relocate(aliquot_barcode, .before =ce1)
 
 
 tcga_id_map_tatlow_piccolo <- read_csv("/home/lythgo02/ecotyper/downloading_ecotyper_data/Tatlow_and_Piccolo_2016/TCGA_ID_MAP.csv") %>% clean_names() %>%
   as.data.frame() %>% 
   dplyr::filter(disease=="OV")

author_ecotype_abundances_mapped <- full_join(author_ecotype_abundances, tcga_id_map_tatlow_piccolo) %>% 
  dplyr::filter(disease=="OV") %>% 
  na.omit() %>%  mutate_at(c('ce1', 'ce2', 'ce3', 'ce4', 'ce5', 'ce6', 'ce7', 'ce8', 'ce9', 'ce10'), as.numeric)  #266 from the author_ecotype_abundances match up to IDs from the Tatlow and Piccolo ID map (Luca and Steen only included 266 TCGA ovarian cancer samples in their analysis so this makes sense)
 

```

```{r}
ecotype_assignment_3_median_all_proportions <- ecotype_assignment_3_median_all %>% 
  group_by(assigned_ce) %>% 
  tally() %>% 
  dplyr::rename(my_analysis=n) 
ecotype_assignment_3_median_all_proportions$my_analysis <- as.numeric(ecotype_assignment_3_median_all_proportions$my_analysis)

newrow <- c("Unassigned", 126)
ecotype_assignment_3_median_all_proportions <- rbind(ecotype_assignment_3_median_all_proportions, newrow) 
ecotype_assignment_3_median_all_proportions <-  ecotype_assignment_3_median_all_proportions %>%  adorn_percentages("col") # convert counts to percentages
  
me <- ggplot(ecotype_assignment_3_median_all_proportions, aes(x=assigned_ce, y=my_analysis, fill=assigned_ce)) +
  geom_col() +
  theme_bw() + 
  xlab("Carcinoma Ecotype") + 
  ylab("%") +
  ggtitle("My analysis: n=430 OV samples assigned to CE") +
  theme(legend.position = "none")

author_ecotype_assignment_proportions <- author_ecotype_abundances_mapped %>% 
  group_by(assigned_ce) %>% 
  tally() %>% 
  dplyr::rename(author_analysis = n) %>% 
  adorn_percentages("col")) # convert counts to percentages

author <- ggplot(author_ecotype_assignment_proportions, aes(x=assigned_ce, y=author_analysis, fill=assigned_ce)) +
  geom_col() +
  theme_bw() + 
  xlab("Carcinoma Ecotype") + 
  ylab("%") +
  ggtitle("Their analysis: n=266 OV samples analysed") +
  theme(legend.position = "none")

gridExtra::grid.arrange(me, author)
```

```{r}

ecotype_assignment_proportions <- full_join(author_ecotype_assignment_proportions, ecotype_assignment_3_median_all_proportions)

#need to make long data wide and then plot on the same graph

library(reshape2)
# reshape data from wide to long format
long <- melt(ecotype_assignment_proportions, c("assigned_ce")) %>% dplyr::rename(proportion=value)
long$proportion <-as.numeric(long$proportion)
  
ggplot(long, aes(assigned_ce, proportion, fill=variable, color = variable)) + 
   geom_col(position = "dodge")
```

```{r identifying OV samples shared between my analysis and the author's analysis}
ecotype_abundance_3_median_all <- read.table("Tatlow_and_Piccolo_2016/ecotyper_output/130522_tatlow_piccolo_2016_for_ecotyper_3_median_all/tatlow_picollo_2016_for_ecotyper_3_median_all_transcripts/Ecotypes/ecotype_abundance.txt")
#the table contains CGhub analysis IDs as identifiers with different punctuation to the example data provided by the authors


#tranpose table
ecotype_abundance_3_median_all_long <- data.table::transpose(ecotype_abundance_3_median_all)
#redefine row and column names
rownames(ecotype_abundance_3_median_all_long) <- colnames(ecotype_abundance_3_median_all)
colnames(ecotype_abundance_3_median_all_long) <- rownames(ecotype_abundance_3_median_all)

ecotype_abundance_3_median_all_long <- ecotype_abundance_3_median_all_long  %>% rownames_to_column( var = "rowname")
#ecotype_abundance_3_median_all_long$rowname <-  str_replace_all(ecotype_abundance_3_median_all_long$rowname, "\\.", "-") %>% as_vector()
ecotype_abundance_3_median_all_long$cg_hub_analysis_id <- str_replace_all(ecotype_abundance_3_median_all_long$rowname, "\\.", "-")
ecotype_abundance_3_median_all_long$cg_hub_analysis_id <- str_replace_all(ecotype_abundance_3_median_all_long$cg_hub_analysis_id, "_median", "") 
teast <- left_join(tcga_id_map_tatlow_piccolo, ecotype_abundance_3_median_all_long)
#create a list of the 266 cd_analysis_hub_id present in the author's analysis 
author_id_list <- author_ecotype_abundances_mapped[,-2:-12] # extracting the IDs I am interested in

#match to the id in my analysis 
eco_abund_3_median_all_long_filtered <- left_join(author_id_list, ecotype_abundance_3_median_all_long) %>% 
                                        remove_missing() %>% 
                                        dplyr::select(-aliquot_id, -aliquot_barcode, -disease, -rowname) %>%   
                                        column_to_rownames("cg_hub_analysis_id")  %>%  
                                        clean_names()
shared_id <- eco_abund_3_median_all_long_filtered$rowname %>% as.data.frame() %>% dplyr::rename("cg_hub_analysis_id"=".")
shared_id$cg_hub_analysis_id <- str_replace_all(shared_id$cg_hub_analysis_id, "_median", "")
shared_id$cg_hub_analysis_id <- str_replace_all(shared_id$cg_hub_analysis_id, "\\.", "-")

author_abundances_filtered <- subset( author_ecotype_abundances_mapped, author_ecotype_abundances_mapped$cg_hub_analysis_id %in% shared_id$cg_hub_analysis_id) %>% 
   dplyr::select(-aliquot_id, -aliquot_barcode, -disease, -assigned_ce) %>% 
  column_to_rownames("cg_hub_analysis_id")
```

#need to check if the 99 that matchh are the same ones that matc when I check with TCGA aliquot barcode

```{r Chi sqaured test for similarity between results}

#author_analysis_samples_in_common <- subset(author_ecotype_abundances_mapped,author_ecotype_abundances_mapped$cg_hub_analysis_id %in% ecotype_abundance_3_median_all_long$cg_hub_analysis_id)  %>% 
 # dplyr::select(-aliquot_id, -aliquot_barcode, -disease, -assigned_ce) %>%   column_to_rownames("cg_hub_analysis_id")# keep only the rows from author_ecotype_abundances_mapped for which the cg_hub_analysis_id also appears in ecotype_abundance_median_all_long

#not sure why the IDs don't match between tables

#my_analysis_samples_in_common <- subset(ecotype_abundance_3_median_all_long, ecotype_abundance_3_median_all_long$cg_hub_analysis_id %in% author_ecotype_abundances_mapped$cg_hub_analysis_id) %>% 
 #  dplyr::select(-rowname) %>% 
  #rownames_to_column() %>%  
  #dplyr::select(-rowname) %>% 
 # column_to_rownames("cg_hub_analysis_id") %>% clean_names()# keep only the rows from ecotype_abundance_median_all_long for which the cg_hub_analysis_id also appears in  author_ecotype_abundances_mapped

expected <- (round(author_abundances_filtered*100) +1) %>% write_csv("expected.csv")

observed <- (round(eco_abund_3_median_all_long_filtered *100)+1) %>% write_csv("observed.csv")

observed_vetor <- as_vector(observed[1,]) %>% unname()
expected_proportions <- as_vector(eco_abund_3_median_all_long_filtered[1,]) %>% unname()

chisq.test(x=observed, p=expected_proportions)

results <- c() # initialise the variable for use in the loop

for (i in 1:nrow(observed)) { #for as many elements as there are in the observed table
observed_vector <- unname(as_vector(observed[i,])) #chi squared function will only work on unnamed vectors
expected_proportions <- unname(as_vector(eco_abund_3_median_all_long_filtered[j,])) #to pull out the expected proportions of each ecotype in that sample (is the raw ecotyper results)
results <- rbind(results, chisq.test(x=observed_vector, p=expected_proportions)) } # put the results of the chi squared test on each row into a new table

```

```{r}
for (i in 1:10){
    for (j in 1:5){
        print(i*j)
    }
}
```

